//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace magazyn.Areas.Magazine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Items_has_OrderList = new HashSet<Items_has_OrderList>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Telephone { get; set; }
        public string City { get; set; }
        public string Adress { get; set; }
        public Nullable<int> Id_Magazine { get; set; }
    
        public virtual Magazine Magazine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items_has_OrderList> Items_has_OrderList { get; set; }
    }
}
