//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace magazyn.Areas.Magazine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items_has_OrderList
    {
        public int Id { get; set; }
        public Nullable<int> Id_Items { get; set; }
        public Nullable<int> Id_OrderList { get; set; }
        public Nullable<int> Id_Employees { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Items Items { get; set; }
        public virtual OrderList OrderList { get; set; }
    }
}
